name: Build SimpleSvm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSVC and WDK
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          
      - name: Build
        shell: cmd
        run: |
          mkdir build\output build\obj
          
          set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\km;C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\um;%INCLUDE%
          set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\km\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64;%LIB%
          
          ml64.exe /c /Fo build\obj\x64.obj x64.asm
          cl.exe /nologo /O2 /GS- /c /D_AMD64_ /D_WIN64 /Fo build\obj\SimpleSvm.obj SimpleSvm.cpp
          link.exe /nologo /out:build\output\SimpleSvm.sys /driver /entry:DriverEntry /subsystem:native build\obj\*.obj
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SimpleSvm.sys
          path: build\output\*.sys
